package com.mazexiang.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.departmentName
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    private String departmentname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.id
     *
     * @return the value of tb_department.id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.id
     *
     * @param id the value for tb_department.id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.departmentName
     *
     * @return the value of tb_department.departmentName
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.departmentName
     *
     * @param departmentname the value for tb_department.departmentName
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }
}