package com.mazexiang.bean;

import javax.validation.constraints.Email;
import javax.validation.constraints.Pattern;

public class Employee {

    private Integer id;

    @Pattern(regexp = "(^[a-zA-Z0-9_-]{6,16}$)",message = "用户名必须是6-16位的英文或数字组合")//pattern表示自定义的校验规则
    private String lastName;


    private String gender;

    @Pattern(regexp = "^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$",message = "邮箱格式不正确")
    private String email;

    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.id
     *
     * @return the value of tb_employee.id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.id
     *
     * @param id the value for tb_employee.id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.last_name
     *
     * @return the value of tb_employee.last_name
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.last_name
     *
     * @param lastName the value for tb_employee.last_name
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.gender
     *
     * @return the value of tb_employee.gender
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.gender
     *
     * @param gender the value for tb_employee.gender
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.email
     *
     * @return the value of tb_employee.email
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.email
     *
     * @param email the value for tb_employee.email
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.dept_id
     *
     * @return the value of tb_employee.dept_id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.dept_id
     *
     * @param deptId the value for tb_employee.dept_id
     *
     * @mbggenerated Wed Sep 20 21:13:17 CST 2017
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public Employee(Integer id, String lastName, String gender, String email, Integer deptId) {
        this.id = id;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        this.deptId = deptId;
    }

    public Employee() {
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", lastName='" + lastName + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", deptId=" + deptId +
                '}';
    }
}